# Profil pour le développement local
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    root: INFO
    com.howners: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
