package com.howners.gestion.domain.notification;

public enum NotificationType {
    PAYMENT_DUE,
    PAYMENT_REMINDER,
    CONTRACT_EXPIRY,
    APPLICATION_RECEIVED,
    SIGNATURE_REQUESTED,
    SIGNATURE_COMPLETED,
    PAYMENT_OVERDUE,
    APPLICATION_ACCEPTED,
    APPLICATION_REJECTED,
    RENT_REVISION,
    CHARGE_REGULARIZATION,
    MISE_EN_DEMEURE,
    REFERRAL_REWARD,
    RATING_RECEIVED,
    DOCUMENT_SHARED,
    DPE_EXPIRY,
    INSURANCE_RENEWAL,
    LEASE_END,
    SYSTEM
}
